### ISSUE TITLE
homebrew install fails for no obvious reason

### ISSUE THREAD

**Issue by ghost** [dholm/homebrew-sdr#6] opened 2015-07-25 09:29 UTC
Ok, not a homebrew expert here, but 'brew install liquid-dsp' gives me:

_bash-3.2$ brew install liquid-dsp_
_==> Installing liquid-dsp from dholm/homebrew-sdr_
_==> Downloading https://github.com/jgaeddert/liquid-dsp/archive/v1.2.0.tar.gz_
_Already downloaded: /Library/Caches/Homebrew/liquid-dsp-1.2.0.tar.gz_
_==> ./configure --prefix=/usr/local/Cellar/liquid-dsp/1.2.0_
_2015-07-25 11:20:41 +0200_
- *
  _./configure_
  _--prefix=/usr/local/Cellar/liquid-dsp/1.2.0_
- *
  _Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-_dir=/usr/include/c++/4.2.1*
- *
  _READ THIS: https://git.io/brew-troubleshooting_
  _If reporting this issue please do so at (not Homebrew/homebrew):_
  _https://github.com/dholm/homebrew-sdr/issues_

gist-logs here: https://gist.github.com/f950f509f4dda2d116d2

**Comment by dholm** [comment] 2015-08-22 10:26
@Toontje Hi, can you run `brew install -v liquid-dsp` and make another gist of the output?

**Comment by dholm** [comment] 2015-08-22 10:41
I'm closing this issue as a duplicate of #4.  Please reopen if that is not the case.

**Closed as completed by dholm** 2015-08-22 10:41 UTC
Labels: duplicate
